language: node_js
node_js:
- 10
cache:
- npm
install:
- npm i
deploy:
  api_key:
    secure: ltyxv7HAs5Dxi/q74+MdypzuevMmjR/2BVoZaFHVaxZTscQmHI8ZoxWrd1lWuLNNMNw5P9ZKeLC9+0yl/QxHL1GsLh7zCj9uLXbnXVHgZvx/NOP0CAyNd9iwQHKXFr31qwO7wF8iQ7QVDTNTHYrXwj4KudVUEJIY/qL016jOhPIr7TurtSAF4TN26T5tO03o6XlXkJkR3ny7WuJqNVXTiTilb0NyZs+940LwjMYmi5ogJFvuw2UplJfXBKmYIpdnktJXMLd50eLTfC54RJeegWeifES1pnvCiB0pXZFdSDWQE802fakb+cTJ+isVhpK/yVsNAnJoSCwKMXhj4zZ7wCN3e68HUfIlQwsz7kwJNVfjG9vhM8hM033Tvg16xInvrjhBUuhSTPMkQoqvL34jz1105uLXvcfZNU6IRKPpQ/ulHe18AxO8vFfhJR2CwMul0gZBDhniZCmcYWokrBSjptdKol/8cm2Q/3Kdf5rdWwnS6lsibSH8am0is54PTdV6II5Ujja6gTCvEHWmypgutLMjhQbj/l3CwglwpxtFS5vNf9EvYVreMBLdWLdoHHVJPijTyw2EJDXRMrGTXMK7tW6zvyHDQpGgZQIWtKn8VvzmnWNvjKO2L9jiRJ7pAvRCb76r6Ny1BUJuxS6WIupgXadl370IDsM30nsvJavKL84=
    app: momsif